name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO(tmattio) - Fix windows build
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache esy dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: _export
          key: ${{ runner.OS }}-build-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install esy
        run: npm install -g @esy-nightly/esy@latest

      - name: Import dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: esy import-build _export/*

      - name: Install dependencies
        run: esy install

      - name: Build
        run: esy build

      - name: Check formatting
        run: |
          esy format
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are differences:"
            git status --porcelain
            echo "----"
            echo ""
            echo 'Please run `esy format` locally to fix the issues.'
            exit 1
          fi
        # Run formatting check only once
        if: matrix.os == 'ubuntu-latest'

      - name: Run tests
        run: esy test

      - name: Export dependencies
        run: esy export-dependencies
